behaviors:
  CubeAgentRays: 
    trainer_type: ppo
    hyperparameters:
      batch_size: 256        
      buffer_size: 5120        
      learning_rate: 3.0e-4  
      beta: 5.0e-4             
      epsilon: 0.2            
      lambd: 0.99             
      num_epoch: 3           
      learning_rate_schedule: linear
    network_settings:
      normalize: true          
      hidden_units: 128        
      num_layers: 2            
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 128          
    max_steps: 3000000          
    summary_freq: 10000